### ISSUE TITLE
It only works in debug mode for flutter web

### ISSUE THREAD

**Issue by patricknicolosi** [KabirKwatra/cloud_firestore_all#12]
It only works in debug mode for flutter web. How can I solve it?

**Comment by Kab1r** [comment]
Could you share your error message or provide additional details?

**Comment by patricknicolosi** [comment]
I solved, thanks anyway :-))

**Comment by kostas-g** [comment]
how did you resolve it?
Me too I can only run my flutter web app successfully if in debug mode..

getting this error:
 js_helper.dart:1342:36

**Comment by kostas-g** [comment]
huh... for me configuring web/index.html properly did the trick..
