### ISSUE TITLE
Not working on web | Due to import 'dart:ui'

### ISSUE THREAD

**Issue by taharushain** [KabirKwatra/cloud_firestore_all#13]
When running for web it hangs on a blank screen with the message 

> Attempting to connect to browser instance

After a lot of debugging and trying all the channels with the latest builds, I have found the problem to be with the `dart:ui` import in the generated_plugin_registrant.dart file.
```
//
// Generated file. Do not edit.
//

// ignore: unused_import
import 'dart:ui';

import 'package:firebase_auth_web/firebase_auth_web.dart';
import 'package:firebase_core_web/firebase_core_web.dart';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void registerPlugins(PluginRegistry registry) {
  FirebaseAuthWeb.registerWith(registry.registrarFor(FirebaseAuthWeb));
  FirebaseCoreWeb.registerWith(registry.registrarFor(FirebaseCoreWeb));
  registry.registerMessageHandler();
}
```

It appears using 'dart:ui' or 'dart:io' in flutter breaks the web app. Removing any such import from the plugin should solve the problem. Can you please remove this import line from the generated file.

**Comment by Kab1r** [comment]
This project does not include a `generated_plugin_registrant.dart` file.
Please provide additional details about the problem.

**Comment by taharushain** [comment]
@KabirKwatra this file is auto-generated, and I was guessing it was generated by this plugin since it uses firebase

**Comment by Kab1r** [comment]
I think it was generated by one of our dependencies.

**Comment by taharushain** [comment]
Yes it was one of the dependencies, upgrading those solved the problem. Also, the firebase's cloudstore package has now support for web as well.
