### ISSUE TITLE
Does not handle queries on document Ids in web case.

### ISSUE THREAD

**Issue by pslavers** [KabirKwatra/cloud_firestore_all#3]
There is no mechanism for handling a query on the documentId field.
Using firebase/firestore I do the following:
``` 
fs.QuerySnapshot querySnapshot = await _settings.where(fs.FieldPath.documentId(), "==", id).get();
```
Please add this feature.

Thanks.

**Comment by pslavers** [comment]
G'Day,
Thanks.
It is not working.
The following query does not respond:
```    
import 'package:cloud_firestore_all/cloud_firestore_all.dart' as fsa;

print( 'Creating Query with id=$id');
    fsa.Query query = _tasks.where(fsa.FieldPath.documentId(), isEqualTo: id);
print( 'Attempting to get documents');
```
The console shows:
```
Creating Query with id=SU3lQD5dxfuZZNC1MndL

Application finished.
```
The `Application finished.` occurs because I give up and terminate the debug session.
So something is causing the system to hang.

I noticed that your code is:
```
class FieldPath implements intf.FieldPath {
  static dynamic documentId() => web.FieldPath.documentId;
}
```
But I think it should be:
```
class FieldPath implements intf.FieldPath {
  static web.FieldPath documentId() => web.FieldPath.documentId();
}
```
I tested this, and it still didn't work.

Cheers,
Phil.

**Comment by pslavers** [comment]
G'Day,
Found the bug.
Please fix up the line 102 in web/query.dart from:
```
    if (isNull) 
```
to:
```
    if (isNull != null ) 
```
My code is now working.

I will test in Android tomorrow.
Cheers,
Phil.

**Comment by pslavers** [comment]
G'Day,
Happy New Year!!!
The merged Master does not work.
Please correct `fieldValue.dart`:
```
class FieldPath implements intf.FieldPath {
  static dynamic documentId() => web.FieldPath.documentId;
}
``` 
to:
```
class FieldPath implements intf.FieldPath {
  static web.FieldPath documentId() => web.FieldPath.documentId();
}
``` 
The pair of parentheses `()` at the end of `web.FieldPath.documentId();` are crucial.

Also, your change in `query.dart` :
```
    bool isNull = false}) {
```
Does not work, if `isNull` is not used it needs to be `null`, so setting it to false causes other problems.

Please delete this back to:
```
    bool isNull }) {
```
and change:
```
   if (isNull != null) {
      assert( true == isNull );
      op = '==';
      value = null;
    }
```

With these changes, it works.

I have not tested Android yet, but I will once you make these changes.

Thanks for all your help,
Cheers,
Phil.

**Comment by Kab1r** [comment]
isNull is not used if it is false on the web

**Comment by pslavers** [comment]
G'Day,
Everything is working now.
Thanks.

I still think that you should change:
```
    bool isNull }) 
```
and
```
  if (isNull != null) {
      assert( true == isNull );
      op = '==';
      value = null;
    }
```
But, it is working at the moment, so leave it for now.
Thanks again.
I have deleted my fork.
And have closed the issue.
Cheers,
Phil.
