### ISSUE TITLE
DocumentSnapshot.documentID does not seem to exist

### ISSUE THREAD

**Issue by pslavers** [KabirKwatra/cloud_firestore_all#6]
G'Day,
According to the cloud_firestore API (https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/DocumentSnapshot-class.html), there should be a documentID.

I couldn't find it.

Please correct this.
Cheers,
Phil.

**Comment by Kab1r** [comment]
DocumentSnapshot has an [id field](https://pub.dev/documentation/firebase/latest/firebase_firestore/DocumentSnapshot/id.html)

**Comment by Kab1r** [comment]
Some of the fields and methods follow the [firebase package](https://pub.dev/packages/firebase)'s semantics.

**Comment by Kab1r** [comment]
Changing this would cause breaking changes.
